# This is an OpenAPI Specification (https://swagger.io/specification/)
# for gp-connect-user-permissions owned by NHS Digital (https://digital.nhs.uk/)
openapi: 3.0.0
info:
  version: Computed and injected at build time by `scripts/set_version.py`
  title: GP Connect - Patient Permissions
  contact:
    name: GP Connect - Patient Permissions API Support
    url: https://digital.nhs.uk/developer/help-and-support
    email: api.management@nhs.net
  description: |
    ## Overview

    Use this API to manage a patient's permissions to access the medical
    record and services they can access at their GP practice.

    You can:

    - get a patient's permissions
    - request to update a patient's permissions to a higher level

    You cannot:

    - request to update a patient's permissions to a lower level

    To use this API, the end user must be a patient who is:

    - registered with the GP practice
    - registered with NHS login to P9 identity verification level

    This API allows you to manage the permissions for:

    - appointments
    - prescriptions
    - medical record

    ### Access modes

    This API has a single access mode:

    | Access mode                                                                                                                | Functions                                    | Availability |
    | -----------                                                                                                                | ---------                                    | ------------ |
    | [Patient access](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#patient-access-mode) | Get own permissions. Update own permissions. | TBC          |

    For further details about the access modes for this API, see
    [Security and authorisation](#api-description__security-and-authorisation) below.

    ## Who can use this API

    This API:

    - is only for use by patient-facing applications
    - is only for non-clinical use
    - can only be used where there is a legal basis to do so

    Make sure you have a valid use case before you go too far with your development. To do this, contact us.

    You must do this before you can go live (see `Onboarding` below).

    ## Related APIs

    The GP Connect suite of patient facing service (PFS) APIs include the
    following related APIs:

    - [GP Connect appointment management FHIR API](https://digital.nhs.uk/developer/api-catalogue/gp-connect-appointment-management-fhir) - manage GP practice appointments between different systems.
    - GP Connect access record API - retrieve a patient's medical record from the GP practice systems.
    - GP Connect prescriptions management API - manage a patient's prescriptions as held by the GP practice systems.

    ## API status and roadmap

    This API is [in development](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#statuses), meaning:

    - it is available for testing in the integration environment
    - it is not available for production use
    - we might make breaking changes, but only if we cannot avoid it, and we will give advance notice

    To see our roadmap or to suggest, comment or vote on features for this API, see our [interactive product backlog](https://nhs-digital-api-management.featureupvote.com/suggestions/341390/gp-connect-user-permissions).

    If you have any other queries, please [contact us](https://digital.nhs.uk/developer/help-and-support).

    ## Service level

    This API is a silver service, meaning it is operational 24 x 7 x 365 but
    only supported during business hours (8am to 6pm), Monday to Friday
    excluding bank holidays.

    For more details, see [service levels](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#service-levels).

    ## Technology

    This API is [RESTful](https://digital.nhs.uk/developer/guides-and-documentation/our-api-technologies#basic-rest)

    ## Network access

    This API is available on the internet.

    For more details, see [Network access for APIs](https://digital.nhs.uk/developer/guides-and-documentation/network-access-for-apis).

    ## Security and authorisation

    This API is
    [user-restricted](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#user-restricted-apis),
    meaning an end user must be present and authenticated to use it.

    The end user must be:

    - a patient
    - authenticated with NHS login to P9 identity verification level

    The API uses Open ID Connect to authenticate the end user and OAuth 2.0 to
    authorise the calling system. It supports the following security pattern
    using NHS login:

    - [User-restricted RESTful APIs - NHS login separate authentication and authorisation](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/user-restricted-restful-apis-nhs-login-separate-authentication-and-authorisation)

    ## Environments and testing

    | Purpose          | URL                                                         |
    | -------          | ---                                                         |
    | Sandbox          | `https://sandbox.api.service.nhs.uk/gp-connect/permissions` |
    | Integration test | Not yet available                                           |
    | Production       | Not yet available                                           |

    ### Sandbox testing

    Our [sandbox environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#sandbox-testing):

    - is for early developer testing
    - only covers a limited set of scenarios
    - is stateless, so it does not store data
    - is open access, so does not allow you to test authorisation

    For more details on sandbox testing, or to try out the sandbox using our
    "Try this API" feature, see the documentation for each endpoint.

    ### Integration testing (not yet available)

    Our [integration test environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#integration-testing):

    - is for formal integration testing
    - is stateful, so it does persist data
    - includes authorisation

    For more details see
     [integration testing with our RESTful APIs](https://digital.nhs.uk/developer/guides-and-documentation/testing#integration-testing-with-our-restful-apis).

    ## Onboarding

    We are hoping to make the assurance process as lightweight and as
    self-service as possible.

    ## Errors

    We use standard HTTP status codes to show whether an API request succeeded
    or not. They are usually in the range:

    - 200 to 299 if it succeeded, including code 202 if it was accepted by an
      API that needs to wait for further action

    - 400 to 499 if it failed because of a client error by your application

    - 500 to 599 if it failed because of an error on our server

    Errors specific to each API are shown in the Endpoints section, under
    Response. See our
    [reference guide](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#http-status-codes)
    for more on errors.

servers:
  - url: https://sandbox.api.service.nhs.uk/gp-connect/permissions
    description: Sandbox environment

tags:
  - name: Patient Permissions
    description: Patient permissions operations

paths:
  /Patient/{id}:
    parameters:
      - $ref: "#/components/parameters/Id"
      - $ref: "#/components/parameters/BearerAuthorization"
      - $ref: "#/components/parameters/CorrelationID"
      - $ref: "#/components/parameters/RequestID"
    get:
      operationId: getPatientPermissions
      tags:
        - Patient Permissions
      summary: GET a patient's permissions
      description: |
        Get a patient's permissions to access the medical record and services
        they can access at their GP practice.
        Returns an object which includes information about the
        permissions they have to the medical record and services.
      responses:
        200:
          description: Successful response
          headers:
            X-Correlation-ID:
              $ref: "#/components/headers/X-Correlation-ID"
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PatientPermission"
              examples:
                ResponseFullPermissions:
                  $ref: "#/components/examples/ResponseFullPermissions"
                ResponsePendingRequestForDocumentsAccess:
                  $ref: "#/components/examples/ResponsePendingRequestForDocumentsAccess"
                ResponsePendingRequestForFullAcecssAppointments:
                  $ref: "#/components/examples/ResponsePendingRequestForFullAccessAppointments"
                ResponseMultiplePendingRequests:
                  $ref: "#/components/examples/ResponseMultiplePendingRequests"
        4XX:
          description: |
            An error occurred as follows:

            | HTTP status | Error code             | Description                                                                                                                               |
            | ----------- | ----------             | -----------                                                                                                                               |
            | 400         | INVALID_RESOURCE_ID    | Invalid NHS number.                                                                                                                       |
            | 400         | UNSUPPORTED_SERVICE    | Missing NHS number.                                                                                                                       |
            | 400         | MISSING_VALUE          | Missing header parameter. For details, see the `diagnostics` field.                                                                       |
            | 400         | INVALID_VALUE          | Invalid header parameter. For details, see the `diagnostics` field.                                                                       |
            | 401         | ACCESS_DENIED          | Access token missing, invalid or expired, or calling application not configured for this operation.                                       |
            | 403         | ACCESS_DENIED          | Patient cannot perform this action.                                                                                                       |
            | 404         | RESOURCE_NOT_FOUND     | Patient does not exist for given NHS number.                                                                                              |
            | 404         | INVALIDATED_RESOURCE   | Patient did exist for given NHS number, but has been invalidated and not superseded by another NHS number.                                |
            | 408         | UNABLE_TO_CALL_SERVICE | The downstream domain processing has not completed within the configured timeout period.                                                  |
            | 429         | TOO_MANY_REQUESTS      | You have exceeded your application's [rate limit](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#rate-limits). |
          content:
            application/fhir+json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                InvalidRequestError:
                  $ref: "#/components/examples/InvalidRequestError"
                MinimalErrorResponse:
                  $ref: "#/components/examples/MinimalErrorResponse"
    post:
      operationId: updatePatientPermissions
      tags:
        - Patient Permissions
      summary: Request a change to a permission
      description: |
        Request a change to the permission a patient has for their medical
        record or services provided by the GP practice.
        Once a request has been submitted it will be processed, however, due to
        the nature of the request when this will happen is unknown at the time
        of request submission.
        When the request has been processed the result will be apparent in the
        response to getting the permissions.
        The message returned from submitting the request _should_ contain
        information pertinent to when the request may be processed. This could
        be shown to the patient to help set expectations.
      requestBody:
        $ref: "#/components/requestBodies/UpdatePermission"
      responses:
        200:
          description: Successful response
          headers:
            X-Correlation-ID:
              $ref: "#/components/headers/X-Correlation-ID"
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PermissionUpdateResponse"
              examples:
                ResponseRequestForDocumentsAccess:
                  $ref: "#/components/examples/ResponseRequestForDocumentsAccess"
                ResponseRequestToMoveDate:
                  $ref: "#/components/examples/ResponseRequestToMoveDate"
                ResponseRequestPending:
                  $ref: "#/components/examples/ResponseRequestPending"
                ResponseRequestRejected:
                  $ref: "#/components/examples/ResponseRequestRejected"
        4XX:
          description: |
            An error occurred as follows:

            | HTTP status | Error code                      | Description                                                                                                                                                              |
            | ----------- | ----------                      | -----------                                                                                                                                                              |
            | 400         | INVALID_RESOURCE_ID             | Invalid NHS number.                                                                                                                                                      |
            | 400         | UNSUPPORTED_SERVICE             | Missing NHS number.                                                                                                                                                      |
            | 400         | MISSING_VALUE                   | Missing header parameter. For details, see the `diagnostics` field.                                                                                                      |
            | 400         | INVALID_VALUE                   | Invalid header parameter. For details, see the `diagnostics` field.                                                                                                      |
            | 400         | INVALID_UPDATE                  | Malformed request.                                                                                                                                                       |
            | 400         | VALIDATION_ERROR                | This is the "default" error thrown when no others are applicable.                                                                                                        |
            | 400         | UNSUPPORTED_CHARACTERS_IN_FIELD | Invalid value in body of patch request. For details, see the `diagnostics` field.                                                                                        |
            | 400         | ADDITIONAL_PROPERTIES           | The user sent additional properties within the dictionary.                                                                                                               |
            | 400         | UNSUPPORTED_VALUE               | There was an unsupported value in the request. For example sending a request and attempting to set a permission for an unknown permission type such as `communications`. |
            | 401         | ACCESS_DENIED                   | Access token missing, invalid or expired, or calling application not configured for this operation.                                                                      |
            | 403         | FORBIDDEN_UPDATE                | The user is not permitted to make certain requests. For example, no user can request access beyond the level of access denoted by `accessLevelMax`.                      |
            | 403         | ACCESS_DENIED                   | Patient cannot perform this action.                                                                                                                                      |
            | 404         | RESOURCE_NOT_FOUND              | Patient does not exist for given NHS number.                                                                                                                             |
            | 404         | INVALIDATED_RESOURCE            | Patient did exist for given NHS number, but has been invalidated and not superseded by another NHS number.                                                               |
            | 408         | UNABLE_TO_CALL_SERVICE          | The downstream domain processing has not completed within the configured timeout period.                                                                                 |
            | 429         | TOO_MANY_REQUESTS               | You have exceeded your application's [rate limit](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#rate-limits).                                |
          content:
            application/fhir+json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                InvalidRequestError:
                  $ref: "#/components/examples/InvalidRequestError"
                MinimalErrorResponse:
                  $ref: "#/components/examples/MinimalErrorResponse"

components:
  headers:
    X-Correlation-ID:
      schema:
        $ref: "#/components/schemas/CorrelationID"
    X-Request-ID:
      schema:
        $ref: "#/components/schemas/RequestID"

  parameters:
    Id:
      in: path
      name: id
      description: |
        The patient's NHS number. The primary identifier of a patient, unique
        within NHS England and Wales. Always 10 digits and must be a
        [valid NHS number](https://www.datadictionary.nhs.uk/attributes/nhs_number.html).
      required: true
      schema:
        type: string
        example: "9000000009"
    BearerAuthorization:
      in: header
      name: Authorization
      description: |
        An
        [OAuth 2.0 bearer token](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#user-restricted-apis)
        from NHS login.
      required: true
      schema:
        type: string
        format: '^Bearer\ [[:ascii:]]+$'
        example: "Bearer g1112R_ccQ1Ebbb4gtHBP1aaaNM"
    CorrelationID:
      in: header
      name: X-Correlation-ID
      description: |
        An optional ID which you can use to track transactions across multiple
        systems. It can take any value, but we recommend avoiding `.`
        characters.

        Mirrored back in a response header.
      schema:
        $ref: "#/components/schemas/CorrelationID"
    RequestID:
      in: header
      name: X-Request-ID
      description: |
        A globally unique identifier (GUID) for the request, which we use to
        de-duplicate repeated requests and to trace the request if you contact
        our helpdesk.

        Must be a universally unique identifier (UUID) (ideally version 4).
        Mirrored back in a response header.
        If you re-send a failed request, use the same value in this header.
      schema:
        $ref: "#/components/schemas/RequestID"

  schemas:
    CorrelationID:
      $ref: "components/schemas/CorrelationID.yaml"
    RequestID:
      $ref: "components/schemas/RequestID.yaml"
    PatientPermission:
      $ref: "components/schemas/PatientPermission.yaml"
    MedicalRecordPermission:
      $ref: "components/schemas/MedicalRecordPermission.yaml"
    MedicalRecordCurrentPermissionItem:
      $ref: "components/schemas/MedicalRecordCurrentPermissionItem.yaml"
    MedicalRecordHistoricalPermissionItem:
      $ref: "components/schemas/MedicalRecordHistoricalPermissionItem.yaml"
    AppointmentsPermission:
      $ref: "components/schemas/AppointmentsPermission.yaml"
    PrescriptionsPermission:
      $ref: "components/schemas/PrescriptionsPermission.yaml"
    BaseRequest:
      $ref: "components/schemas/BaseRequest.yaml"
    MedicalRecordPermissionRequest:
      $ref: "components/schemas/MedicalRecordPermissionRequest.yaml"
    AppointmentsPermissionRequest:
      $ref: "components/schemas/AppointmentsPermissionRequest.yaml"
    PrescriptionsPermissionRequest:
      $ref: "components/schemas/PrescriptionsPermissionRequest.yaml"
    AppointmentsPermissionUpdate:
      $ref: "components/schemas/AppointmentsPermissionUpdate.yaml"
    PrescriptionsPermissionUpdate:
      $ref: "components/schemas/PrescriptionsPermissionUpdate.yaml"
    MedicalRecordPermissionUpdate:
      $ref: "components/schemas/MedicalRecordPermissionUpdate.yaml"
    PermissionUpdateResponse:
      $ref: "components/schemas/PermissionUpdateResponse.yaml"
    MedicalRecordPermissionUpdateResponse:
      $ref: "components/schemas/MedicalRecordPermissionUpdateResponse.yaml"
    AppointmentsPermissionUpdateResponse:
      $ref: "components/schemas/AppointmentsPermissionUpdateResponse.yaml"
    PrescriptionsPermissionUpdateResponse:
      $ref: "components/schemas/PrescriptionsPermissionUpdateResponse.yaml"
    AppointmentsPermissionTypeEnum:
      $ref: "components/schemas/AppointmentsPermissionTypeEnum.yaml"
    AppointmentsAccessLevelEnum:
      $ref: "components/schemas/AppointmentsAccessLevelEnum.yaml"
    AppointmentsAccessLevelMaxEnum:
      $ref: "components/schemas/AppointmentsAccessLevelMaxEnum.yaml"
    PrescriptionsPermissionTypeEnum:
      $ref: "components/schemas/PrescriptionsPermissionTypeEnum.yaml"
    PrescriptionsAccessLevelEnum:
      $ref: "components/schemas/PrescriptionsAccessLevelEnum.yaml"
    PrescriptionsAccessLevelMaxEnum:
      $ref: "components/schemas/PrescriptionsAccessLevelMaxEnum.yaml"
    MedicalRecordPermissionTypeEnum:
      $ref: "components/schemas/MedicalRecordPermissionTypeEnum.yaml"
    MedicalRecordPermissionSubTypeEnum:
      $ref: "components/schemas/MedicalRecordPermissionSubTypeEnum.yaml"
    MedicalRecordAccessLevelEnum:
      $ref: "components/schemas/MedicalRecordAccessLevelEnum.yaml"
    MedicalRecordAccessLevelMaxEnum:
      $ref: "components/schemas/MedicalRecordAccessLevelMaxEnum.yaml"
    ErrorResponse:
      $ref: "components/schemas/ErrorResponse.yaml"

  examples:
    ResponseFullPermissions:
      summary: Full permissions to medical record and services.
      value:
        medicalRecord:
          effectiveDate: "2022-11-01"
          current:
            accessLevel: full
            accessLevelMax: full
          historical:
            accessLevel: summary
            accessLevelMax: documents
        appointments:
          accessLevel: view
          accessLevelMax: full
        prescriptions:
          accessLevel: order
          accessLevelMax: full
    ResponsePendingRequestForDocumentsAccess:
      summary: Pending request to get documents access to historical record.
      value:
        medicalRecord:
          effectiveDate: "2022-11-01"
          current:
            accessLevel: full
            accessLevelMax: full
          historical:
            accessLevel: summary
            accessLevelMax: documents
        appointments:
          accessLevel: book
          accessLevelMax: book
        prescriptions:
          accessLevel: view
          accessLevelMax: order
        requests:
          - status: pending
            createdDateTime: "2022-10-31T23:59:59+00:00"
            message: Requires review by a healthcare worker.
            accessLevel: documents
            permissionType: medicalRecord
    ResponsePendingRequestForFullAccessAppointments:
      summary: Pending request for full access to appointments.
      value:
        medicalRecord:
          effectiveDate: "2022-11-01"
          current:
            accessLevel: full
            accessLevelMax: full
          historical:
            accessLevel: summary
            accessLevelMax: detailed
        appointments:
          accessLevel: view
          accessLevelMax: book
        prescriptions:
          accessLevel: view
          accessLevelMax: order
        requests:
          - status: pending
            createdDateTime: "2022-10-31T23:59:59+00:00"
            message: Requires review by a healthcare worker.
            accessLevel: full
            permissionType: appointments
    ResponseMultiplePendingRequests:
      summary: Multiple pending requests.
      value:
        medicalRecord:
          effectiveDate: "2022-11-01"
          current:
            accessLevel: full
            accessLevelMax: full
          historical:
            accessLevel: summary
            accessLevelMax: detailed
        appointments:
          accessLevel: view
          accessLevelMax: book
        prescriptions:
          accessLevel: view
          accessLevelMax: order
        requests:
          - status: pending
            createdDateTime: "2022-10-31T23:59:59+00:00"
            message: Requires review by a healthcare worker.
            accessLevel: book
            permissionType: appointments
          - status: pending
            createdDateTime: "2022-10-31T23:59:59+00:00"
            message: Requires review by a healthcare worker.
            accessLevel: detailed
            permissionType: medicalRecord
            subType: historical
    ResponseRequestForDocumentsAccess:
      summary: |
        Request for documents access for historical permissions that is
        pending.
      value:
        permissionType: medicalRecord
        subType: historical
        accessLevel: documents
        status: pending
        message: >-
          Request accepted to update access historical effective
          date to documents.
        createdDateTime: "2022-11-01T00:00:00+00:00"
    ResponseRequestToMoveDate:
      summary: Request to move effectiveDate back to requested date.
      value:
        permissionType: medicalRecord
        subType: current
        accessLevel: full
        effectiveDate: "2021-11-01"
        status: pending
        message: Request received to move effective date to date.
        createdDateTime: "2022-11-01T00:00:00+00:00"
    ResponseRequestPending:
      summary: Request for full access to prescriptions service.
      value:
        permissionType: prescriptions
        accessLevel: full
        status: pending
        message: >-
          Request received for full access to prescriptions service.
        createdDateTime: "2022-11-01T00:00:00+00:00"
    ResponseRequestRejected:
      summary: Request rejected for full access to appointments service.
      value:
        permissionType: prescriptions
        accessLevel: full
        status: rejected
        message: >-
          Request received for full access to prescriptions
          service.
        createdDateTime: "2022-11-01T00:00:00+00:00"
    RequestBodyDocumentAccess:
      summary: |
        Request documents access for medical record historical effective date.
      value:
        permissionType: medicalRecord
        subType: historical
        accessLevel: documents
    RequestBodyDateChange:
      summary: Request effective date is set to date.
      value:
        permissionType: medicalRecord
        effectiveDate: "2022-11-01"
    RequestBodyBookAppointments:
      summary: Request book access to appointments service.
      value:
        permissionType: appointments
        accessLevel: book
    RequestBodyFullPrescriptions:
      summary: Request full access to prescriptions service.
      value:
        permissionType: prescriptions
        accessLevel: full
    InvalidRequestError:
      summary: Invalid request error response.
      value:
        resourceType: OperationOutcome
        meta:
          lastUpdated: "2021-04-14T11:35:00+00:00"
        issue:
          - severity: error
            code: value
            details:
              coding:
                - system: https://fhir.nhs.uk/CodeSystem/Spine-ErrorOrWarningCode
                  version: "1"
                  code: INVALID_VALUE
                  display: Provided value is invalid.
              diagnostics: (invalid_request) firstName is missing.
              expression:
                - /data/attributes/firstName
    MinimalErrorResponse:
      summary: Error response with only the required fields.
      value:
        resourceType: OperationOutcome
        meta:
          lastUpdated: "2022-11-15T11:10:00+00:00"
        issue:
          - severity: error
            code: expired

  requestBodies:
    UpdatePermission:
      description: |
        Object containing information about the permission to update along with
        the `accessLevel` to update to.
      required: true
      content:
        application/json:
          schema:
            description: |
              A request could be for the medical record, appointments service
              or prescriptions service.
            oneOf:
              - $ref: "#/components/schemas/MedicalRecordPermissionUpdate"
              - $ref: "#/components/schemas/AppointmentsPermissionUpdate"
              - $ref: "#/components/schemas/PrescriptionsPermissionUpdate"
            discriminator:
              propertyName: id
              mapping:
                medicalRecord: "#/components/schemas/MedicalRecordPermissionUpdate"
                appointments: "#/components/schemas/AppointmentsPermissionUpdate"
                prescriptions: "#/components/schemas/PrescriptionsPermissionUpdate"
          examples:
            RequestBodyDocumentAccess:
              $ref: "#/components/examples/RequestBodyDocumentAccess"
            RequestBodyDateChange:
              $ref: "#/components/examples/RequestBodyDateChange"
            RequestBodyBookAppointments:
              $ref: "#/components/examples/RequestBodyBookAppointments"
            RequestBodyFullPrescriptions:
              $ref: "#/components/examples/RequestBodyFullPrescriptions"
